git: true
model: gpt-4o
editor: diffs

# Preload these docs as read-only context
read:
  - RepoAI/prompt_system.txt
  - RepoAI/style.md
  - RepoAI/module-map.md
  - RepoAI/.context/latest.md

# Nice-to-haves
dark-mode: true
pretty: true
auto-commits: true

auto-test: false
auto-lint: false
