git: true
gitignore: true
editor: diffs
model: gpt-4o
weak-model: gpt-4o-mini

# Files aider can read/modify
files:
  include:
    - "**/*.swift"
    - "**/*.xcodeproj/**"
    - "**/*.xcworkspace/**"
    - "Package.swift"
    - "README.md"
    - "RepoAI/**/*.md"
    - "RepoAI/prompt_system.txt"
  exclude:
    - "Pods/**"
    - "DerivedData/**"
    - "**/*.xcassets/**"

# Always load these as context
read:
  - RepoAI/prompt_system.txt
  - RepoAI/style.md
  - RepoAI/module-map.md

# Safer defaults for solo development
auto-commits: true      # commits each change automatically
auto-test: false        # don’t run tests automatically
auto-lint: false        # don’t run lint automatically

# cut the prompts:
yes-always: true               # auto-yes to all confirmations
suggest-shell-commands: false  # don’t even suggest/run shell cmds
