git: true
gitignore: true         # optional; safe to keep or omit
editor: diffs
model: gpt-4o
weak-model: gpt-4o-mini

# Solo-friendly defaults
auto-commits: true
auto-test: false
auto-lint: false

# No interactive shell stuff (prevents weird folders)
yes-always: true
suggest-shell-commands: true

# Always load these as context (read-only)
read:
  - RepoAI/prompt_system.txt
  - RepoAI/style.md
  - RepoAI/module-map.md
  - RepoAI/tasks.md                # <- add this

