git: true
gitignore: true         # optional; safe to keep or omit
editor: diffs
model: gpt-4o
weak-model: gpt-4o-mini

# Solo-friendly defaults
auto-commits: true
auto-test: false
auto-lint: false

# No interactive shell stuff (prevents weird folders)
yes-always: true
suggest-shell-commands: false

# Files Aider may read/modify
files:
  include:
    - "**/*.swift"
    - "Package.swift"
    - "README.md"
    - "RepoAI/**/*.md"
    - "RepoAI/prompt_system.txt"
  exclude:
    - "Pods/**"
    - "DerivedData/**"
    - "**/*.xcassets/**"
    - "RepoAI/.log/**"      # optional safety

# Always load these as context (read-only to Aider)
read:
  - RepoAI/prompt_system.txt
  - RepoAI/style.md
  - RepoAI/module-map.md
  # If you ever need project metadata as context (NOT for editing), uncomment:
  # - "EmojiPredictions.xcodeproj/project.pbxproj"
