git: true
gitignore: true         # optional; safe to keep or omit
editor: diffs
model: gpt-4o
weak-model: gpt-4o-mini

# Solo-friendly defaults
auto-commits: true
auto-test: false
auto-lint: false

# No interactive shell stuff (prevents weird folders)
yes-always: true
suggest-shell-commands: false

# Files Aider may read/modify (keep docs read-only to avoid accidental edits)
files:
  include:
    - "**/*.swift"
    - "Package.swift"
    - "README.md"
    - "RepoAI/prompt_system.txt"   # editable if you want
  exclude:
    - "Pods/**"
    - "DerivedData/**"
    - "**/*.xcassets/**"
    - "RepoAI/.log/**"
    - "RepoAI/.context/**"         # <- add this

# Always load these as context (read-only)
read:
  - RepoAI/prompt_system.txt
  - RepoAI/style.md
  - RepoAI/module-map.md
  - RepoAI/tasks.md                # <- add this

Output format:
- Return a unified diff only. No code fences, no shell commands, no extra prose before the diff.
- After the diff, add:
  RATIONALE:
  EDGE CASES: (5 bullets)
